name: Sonar Cloud Result

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    #sonarcloud:
    #    name: SonarCloud
    #    runs-on: ubuntu-latest
    #    steps:
    #    - uses: actions/checkout@v2
    #      with:
    #          fetch-depth: 0  
    #    - name: SonarCloud Scan
    #      uses: SonarSource/sonarcloud-github-action@master
    #      env:
    #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
    #        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    it-:
      name: Integration Test
      runs-on: ubuntu-latest
      #needs: [deployVote]
      steps:
        - uses: actions/checkout@v2
        - name: Building
          run: |
            cd ./ut
            npm install
        - name: testing Vote
          run: |
            cd ./ut
            npx codeceptjs run --steps --reporter mocha-multi
        - name: Publish Integration Test Results
          uses: EnricoMi/publish-unit-test-result-action@v1.4
          if: always()
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            check_name: Integration Test Vote
            comment_title: Integration Test Statistics
            hide_comments: all but latest
            comment_on_pr: true
            files: junit/result.xml
            report_individual_runs: true
            deduplicate_classes_by_file_name: false
    
  
      
      
        
